#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
origin_file=.last-origin 

branch_name="$(git symbolic-ref HEAD 2>/dev/null)"
branch_name=${branch_name##refs/heads/}

current_origin_sha=$(git show origin/"$branch_name" | grep commit -m 1 | awk '{ print $2 }')
saved_origin=`cat $origin_file`

echo ORIGIN $current_origin_sha
echo SAVED_ORIGIN $saved_origin

if [[ $current_origin_sha == "$saved_origin"  ]]; then
    echo "> Same origin."
    exit 0
fi

old_mesage="$(git log -1 --pretty=%B)"

echo "*****"
echo $old_mesage
echo "**-**"
echo $current_origin_sha
echo "*****"

git commit --amend -m "$old_mesage" -m "previous-origin: ${current_origin_sha}"

# echo "$current_origin_sha" > .last-origin

# # last_commit_sha=$(git log | grep commit -m 1 | awk '{ print $2 }');
# git add .last-origin
# git commit -m "fix(last-origin): updated" --no-verify
# # git rebase -i --autosquash $last_commit_sha~1
# git reset HEAD~1 --soft
# git commit --amend --no-edit
